# Generated by Django 4.2.5 on 2023-09-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalDetails',
            new_name='MedicineDetails',
        ),
    ]
