# Generated by Django 4.2.5 on 2023-09-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_App', '0002_rename_medicaldetails_medicinedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicineDetails',
            new_name='MedicalDetails',
        ),
    ]
